/**
 * Content classification: line-ending analysis plus the "should we even look at
 * this file?" heuristics that keep the diff and spell engines out of binaries,
 * generated bundles, and minified output.
 *
 * All of it is pure and string-only. Nothing here reads a file — the CLI and
 * the extension read bytes their own way and hand the decoded text in.
 */

/** The three line-ending conventions a text document can use. */
export type EolKind = "lf" | "crlf" | "cr";

/** Counts of each line ending present in a document. */
export interface EolStats {
  readonly lf: number;
  readonly crlf: number;
  readonly cr: number;
  /** The convention used by the majority of lines, `lf` when there are none. */
  readonly dominant: EolKind;
  /** True when more than one convention appears. */
  readonly mixed: boolean;
  /** True when the text ends with a line terminator. */
  readonly finalNewline: boolean;
}

/**
 * Count line terminators by kind.
 *
 * A single pass, because this runs on every compare and a regex-per-kind would
 * scan a large file three times. A lone `\r` only counts as `cr` when it is not
 * the first half of a `\r\n`.
 */
export function analyzeEol(text: string): EolStats {
  let lf = 0;
  let crlf = 0;
  let cr = 0;
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    if (code === 13 /* \r */) {
      if (text.charCodeAt(i + 1) === 10 /* \n */) {
        crlf++;
        i++;
      } else {
        cr++;
      }
    } else if (code === 10 /* \n */) {
      lf++;
    }
  }

  let dominant: EolKind = "lf";
  if (crlf > lf && crlf >= cr) dominant = "crlf";
  else if (cr > lf && cr > crlf) dominant = "cr";

  const present = (lf > 0 ? 1 : 0) + (crlf > 0 ? 1 : 0) + (cr > 0 ? 1 : 0);
  const last = text.charCodeAt(text.length - 1);
  return {
    lf,
    crlf,
    cr,
    dominant,
    mixed: present > 1,
    finalNewline: text.length > 0 && (last === 10 || last === 13),
  };
}

/** The literal terminator string for an `EolKind`. */
export function eolString(kind: EolKind): string {
  return kind === "crlf" ? "\r\n" : kind === "cr" ? "\r" : "\n";
}

/**
 * Rewrite every line terminator to a single convention.
 *
 * Used when `ignoreEol` is set so a CRLF file and an otherwise identical LF
 * file compare as equal, and by formatter adapters that must not silently
 * rewrite a repository's line endings.
 */
export function normalizeEol(text: string, kind: EolKind = "lf"): string {
  const target = eolString(kind);
  return text.replace(/\r\n|\r|\n/g, target);
}

/**
 * True when the text looks like binary content rather than source.
 *
 * Uses the same rule git does: a NUL byte inside the leading window means
 * binary. Decoded UTF-16 text also produces U+FFFD replacement characters when
 * misdecoded as UTF-8, so a high density of those is treated as binary too — a
 * legitimate source file has very few.
 *
 * The window is bounded so classification stays O(1) on a 500 MB file.
 */
export function isProbablyBinary(text: string, sampleBytes = 8_192): boolean {
  const limit = Math.min(text.length, sampleBytes);
  if (limit === 0) return false;

  let replacements = 0;
  let control = 0;
  for (let i = 0; i < limit; i++) {
    const code = text.charCodeAt(i);
    if (code === 0) return true;
    if (code === 0xfffd) replacements++;
    // Control characters excluding tab, LF, CR and form feed.
    else if (code < 32 && code !== 9 && code !== 10 && code !== 12 && code !== 13) control++;
  }
  return replacements / limit > 0.1 || control / limit > 0.3;
}

/**
 * Markers conventionally placed by code generators. Matching is
 * case-insensitive and confined to the head of the file, where these banners
 * are written by convention.
 */
const GENERATED_MARKERS: readonly RegExp[] = [
  /@generated\b/i,
  /\bdo not edit\b/i,
  /\bautogenerated\b/i,
  /\bauto-generated\b/i,
  /\bthis file was generated\b/i,
  /\bcode generated by\b/i,
  /\bgenerated by (?:protoc|swagger|openapi|graphql|prisma|drizzle)\b/i,
];

/**
 * True when the head of the file carries a generator banner.
 *
 * Only the first `headLines` lines are examined: the phrase "do not edit"
 * appears in ordinary prose often enough that scanning a whole document would
 * produce false positives.
 */
export function isProbablyGenerated(text: string, headLines = 20): boolean {
  let end = -1;
  let seen = 0;
  for (let i = 0; i < text.length; i++) {
    if (text.charCodeAt(i) === 10) {
      seen++;
      if (seen >= headLines) {
        end = i;
        break;
      }
    }
  }
  const head = end < 0 ? text.slice(0, 4_096) : text.slice(0, end);
  return GENERATED_MARKERS.some((re) => re.test(head));
}

/** Result of the minification heuristic, with the evidence that produced it. */
export interface MinifiedVerdict {
  readonly minified: boolean;
  readonly averageLineLength: number;
  readonly longestLineLength: number;
  readonly lineCount: number;
}

/**
 * Detect minified or bundled output by line geometry.
 *
 * Minified files are characterised by very few, very long lines. Two signals
 * are combined so that neither alone produces a false positive:
 *
 *   - a mean line length far above what hand-written source reaches, and
 *   - at least one line long enough that no formatter would have produced it.
 *
 * A long single-line JSON fixture is correctly classified as minified, which is
 * what we want: refining a character diff across a 2 MB single line is exactly
 * the pathological case this guards.
 */
export function analyzeMinified(
  text: string,
  averageThreshold = 500,
  longestThreshold = 5_000,
): MinifiedVerdict {
  if (text.length === 0) {
    return { minified: false, averageLineLength: 0, longestLineLength: 0, lineCount: 0 };
  }

  let lineCount = 1;
  let longest = 0;
  let current = 0;
  for (let i = 0; i < text.length; i++) {
    if (text.charCodeAt(i) === 10) {
      if (current > longest) longest = current;
      current = 0;
      lineCount++;
    } else {
      current++;
    }
  }
  if (current > longest) longest = current;

  const average = text.length / lineCount;
  return {
    minified: average > averageThreshold && longest > longestThreshold,
    averageLineLength: average,
    longestLineLength: longest,
    lineCount,
  };
}

/** Convenience boolean wrapper around `analyzeMinified`. */
export function isProbablyMinified(text: string): boolean {
  return analyzeMinified(text).minified;
}

/** Why a document was refused by a size or content guard. */
export type ContentRejection = "binary" | "too-large" | "too-many-lines";

export interface ContentLimits {
  /** Maximum UTF-16 code units. */
  readonly maxLength?: number;
  /** Maximum number of lines. */
  readonly maxLines?: number;
  /** Reject binary-looking content. Defaults to true. */
  readonly rejectBinary?: boolean;
}

/**
 * Apply size and content guards, returning the reason for refusal or
 * `undefined` when the document is safe to process.
 *
 * Returning a reason rather than throwing lets callers report a specific,
 * actionable message ("file is 40 MB, above the 5 MB compare limit") instead of
 * a generic failure.
 */
export function checkContentLimits(
  text: string,
  limits: ContentLimits = {},
): ContentRejection | undefined {
  if ((limits.rejectBinary ?? true) && isProbablyBinary(text)) return "binary";
  if (limits.maxLength !== undefined && text.length > limits.maxLength) return "too-large";
  if (limits.maxLines !== undefined) {
    let lines = 1;
    for (let i = 0; i < text.length; i++) {
      if (text.charCodeAt(i) === 10 && ++lines > limits.maxLines) return "too-many-lines";
    }
  }
  return undefined;
}
