blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/aniketsoni1/code-trio-compare-beautify-spellcheck/discussions
    about: Ask questions or discuss ideas in Discussions.
